
```{r}
library(neuroCombat)
```


```{r}
processed_path <- "./data/processed/"


load_subcortical_data <- function(fpath) {
  arrow::read_parquet(fpath) |>
    tidyr::drop_na(starts_with("mr_y_smri"))
}
included_data <- load_subcortical_data(paste0(processed_path, "processed_tabular.parquet"))
```





```{r}
pivot_to_matrix <- function(df) {
    df |>
        dplyr::select(participant_id, starts_with("mr_y_smri"), -contains("icv")) |>
        dplyr::distinct(participant_id, .keep_all = TRUE) |>
        tidyr::pivot_longer(-participant_id, names_to = 'feature') |>
        tidyr::pivot_wider(
            id_cols = feature,
            names_from = participant_id,
            values_from = value
        ) |>
        tibble::column_to_rownames(var = "feature")
}

```

```{r}
mod <- model.matrix(~ age + sex, data = included_data)
batch <- as.numeric(as.factor(included_data$scanner_serial))

subvolume_combat <- neuroCombat(dat = tmp, batch = batch, mod = mod)
```


```{r}
pivot_to_dataframe <- function(combat_result) {
  combat_result$dat.combat |>
    as.data.frame() |>
    tibble::rownames_to_column() |>
    tidyr::pivot_longer(-rowname, names_to = 'participant_id') |>
    tidyr::pivot_wider(
      id_cols = participant_id,
      names_from = rowname,
      values_from = value
    )
}
```