
```{r}
source("./R/data.R")
```


```{r}
count_available <- function(df, indicator_var = "mr_y_qc__incl__smri__t1_indicator") {
    df %>%
        # filter(.data[[indicator_var]] == 1) %>%
        distinct(participant_id, session_id) %>%
        group_by(session_id) %>%
        count()
}

processed_path <- "./data/processed/full_dataset.parquet"
df <- arrow::read_parquet(processed_path)
```



```{r}
tmp <- df %>%
    filter_mri_qc() %>%
    limit_to_bio_mom() %>%
    summarize_ksads_dep_sx()
tmp
```


```{r}
tmp
```

```{r}
subset_baseline <- function(df) {
  df %>%
    filter(session_id == 'baseline') %>%
    select(
      participant_id,
      sex,
      age = ab_g_dyn__visit_age,
      site = ab_g_dyn__design_site,
      scanner_serial,
      family_id = ab_g_stc__design_id__fam,
      baseline_maternal_asr_int,
      baseline_maternal_asr_anxdep
    )
}

subset_timepoint <- function(
  df,
  timepoints = c("year_2"),
  var_string = "mr_y_smri"
) {
  n_vars <- df %>% select(contains(var_string)) %>% ncol()

  tmp <- df %>%
    filter(session_id %in% timepoints) %>%
    filter_mri_qc() %>%
    select(
      participant_id,
      session_id,
      contains(var_string)
    ) %>%
    tidyr::pivot_wider(
      id_cols = participant_id,
      names_from = session_id,
      values_from = contains(var_string)
    )

  if (n_vars < 2) {
    return(
      tmp %>%
        rename_with(
          ~ paste0(var_string, "_", .x),
          .cols = -c(participant_id)
        )
    )
  } else {
    return(tmp)
  }
}

# subset_follow_up <- function(df, timepoints = c("year_4")) {
#   df %>%
#     filter(session_id %in% timepoints) %>%
#     select(
#       participant_id,
#       session_id,
#       mh_y_bpm__int_sum
#     )
# }

format_subset <- function(df, timepoint_map, sex_map) {
  tmp <- df %>%
    mutate(
      session_id = recode(session_id, !!!timepoint_map),
      sex = recode(ab_g_stc__cohort_sex, !!!sex_map),
      scanner_serial = factor(mr_y_adm__info__dev_serial)
    )
  tmp %>%
    subset_baseline() %>%
    join_tables(
      subset_timepoint(
        tmp,
        timepoints = c("year_2"),
        var_string = "mr_y_smri"
      )
    ) %>%
    join_tables(
      subset_timepoint(
        tmp,
        timepoints = c("year_4"),
        var_string = "mh_y_bpm__int"
      )
    ) %>%
      tidyr::drop_na() %>%
      str()
}


format_subset(tmp, timepoint_map, sex_map)
```



```{r}
df <- arrow::read_parquet(paste0("./data/processed/processed_tabular.parquet"))
```