---
title: "Depression Exploration"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)

source("./R/plot.R")
```


```{r}
df <- arrow::read_parquet("./data/processed/harmonized_tabular.parquet")
df
```


## Explore depression over time


```{r}
# reshape_for_plotting(df) %>%
#   plot_cbcl_by_sex()

reshaped <- reshape_for_plotting(df)
reshaped

```


```{r}
df %>%
  select(
    mh_y_bpm__int_sum,
    total_ksads_dep_sx,
    mh_p_cbcl__synd__wthdep_sum,
    mh_p_cbcl__synd__int_sum
  ) %>%
  rename_with(everything(), .fn = ~outcomes_map)
```

```{r}
make_pairplot <- function(df, outcomces_map, title = "") {
  scale_agreement <- function(data, mapping) {
    x_var <- rlang::as_name(mapping$x)
    y_var <- rlang::as_name(mapping$y)
    
    cor_val <- cor(data[[x_var]], data[[y_var]], use = "complete.obs")
    
    ggplot(data = data, mapping = mapping) +
      geom_point(alpha = 0.05) +
      geom_smooth(method = 'lm') +
      annotate("text", x = Inf, y = Inf, 
              label = sprintf("r = %.2f", cor_val),
              hjust = 1.1, vjust = 1.5)
    }

  df %>%
    select(
      mh_y_bpm__int_sum,
      total_ksads_dep_sx,
      mh_p_cbcl__synd__wthdep_sum,
      mh_p_cbcl__synd__int_sum
    ) %>%
      rename_with(everything(), .fn = ~outcomes_map) %>%
      GGally::ggpairs(
        lower = list(continuous = scale_agreement),
        upper = list(continuous = "blank"),
        diag = list(continuous = "barDiag"),
        switch = "both"
      ) +
        theme_minimal() +
        labs(title = title)
}

make_pairplot(df, outcomes_map, "Depression Symptoms (all time points)")

ggsave("./reports/figures/mh_correlation_all.png", dpi = 'retina', width=8, height=8)

```


```{r}
tpts <- c("baseline", "year_2", "year_4", "year_6")
fpath <- "./reports/figures/"
for (tpt in tpts) {
  title <- paste0("Depression Symptoms (", tpt, ")")
  fname <- paste0(fpath, "mh_correlation_", tpt, ".png")
  
  make_pairplot(df, outcomes_map, title)
  ggsave(fname, dpi = "retina", width=8, height=8)
}

```


```{r}



```

```{r}




# plot_cbcl_by_sex <- function(plot_df) {
#   ggplot(plot_df, aes(x = age, y = masked_summary_score)) +
#     geom_point(alpha = 0.01) +
#     geom_vline(
#       aes(xintercept = median_age, color = factor(median_age)),
#       linetype = "dashed") +
#     facet_wrap(~summary_score, scales='free') +
#     geom_smooth(aes(color = sex)) +
#   scale_color_discrete(
#     labels = setNames(
#       c("Baseline", "Year 2", "Year 4", "Year 6"),
#       sort(unique(plot_df$median_age))
#     )
#   ) +
#     labs(
#       color = "",
#       x = "Age (years)",
#       y = "Summary Scale Value",
#       caption = "CBCL values >= 2sd above the mean removed for plotting"
#     ) +
#     theme_minimal()
# }


```



```{r}


```


```{r}
brain_map <- c(
  "mr_y_smri__vol__aseg__ag__lh_sum.combat" = "Left Amygdala Volume",
  "mr_y_smri__vol__aseg__ag__rh_sum.combat" = "Right Amygdala Volume",
  "mr_y_smri__vol__aseg__hc__lh_sum.combat" = "Left Hippocampus Volume",
  "mr_y_smri__vol__aseg__hc__rh_sum.combat" = "Right Hippocampus Volume"
)

reshape_for_brain_plotting <- function(reshaped) {
  tmp <- reshaped %>%
    select(
      participant_id,
      session_id,
      age,
      summary_score,
      summary_score_value = value,
      ends_with("combat"),
      -ends_with('serial'), 
      -contains("icv"))%>%
    tidyr::pivot_longer(
      cols = ends_with("combat"),
      names_to = 'structure',
      values_to = 'volume'
    ) %>%
    mutate(structure = recode(structure, !!!(brain_map)))
    
  
  tmp %>%
    group_by(structure) %>%
    summarize(
      mean_brain = mean(volume),
      brain_twosd = sd(volume) * 2) %>%
    right_join(tmp, by = 'structure') %>%
    mutate(volume_masked = ifelse(
      volume > mean_brain + brain_twosd |
        volume <= mean_brain - brain_twosd,
      NA, volume))
}

tmp <- reshape_for_brain_plotting(reshaped)
tmp

```


```{r}
ggplot(tmp, aes(x = summary_score_value)) +
  geom_histogram() +
  facet_wrap(~summary_score)
```


```{r fig.width=12}
plot_mh_by_brain <- function(
    df, 
    structure_string = 'Hippocampus', 
    alpha = 0.25, 
    transform = "log1p",
    color_label = "Log Summary Score Value"){
  df %>%
    filter(stringr::str_detect(structure, structure_string)) %>%
    ggplot(aes(x = age, y = volume_masked, color = summary_score_value)) +
      geom_point(alpha = alpha) +
      scale_color_viridis_c(transform = transform) +
      facet_grid(
        rows = vars(summary_score),
        cols = vars(structure)
      ) +
      theme(
        legend.position = "top",
        legend.key.width = unit(2, "cm"),   # make legend bar wider
        legend.text = element_text(size = 10)  # bigger text
    ) +
    labs(
      color = color_label,
      y = "Volume",
      x = "Age (years)"
    ) +
    theme_minimal()
}

plot_mh_by_brain(tmp)

```


